=== php/php-src/pear/package.dtd
<!--
     $Id: package.dtd,v 1.6.2.1 2001-08-28 11:40:56 ssb Exp $

     This is the PEAR package description, version 1.1b1.
     It should be used with the informal public identifier:

         "-//PHP Group//DTD PEAR Package 1.1b1//EN//XML"

     Copyright (c) 1997-2001 The PHP Group             

     This source file is subject to version 2.02 of the PHP license,
     that is bundled with this package in the file LICENSE, and is
     available at through the world-wide-web at
     http://www.php.net/license/2_02.txt.
     If you did not receive a copy of the PHP license and are unable to
     obtain it through the world-wide-web, please send a note to
     license@php.net so we can mail you a copy immediately.

     Authors:
         Stig S. Bakken <ssb@fast.no>

  -->
<!--============== attributes present in all elements ======================-->
<!ENTITY % global.atts "id		ID	#IMPLIED">
<!--============== attributes common to several elements ===================-->
<!ENTITY % role.atts "Role		(php|ext|test|doc) 'php'">
<!ENTITY % extension.atts "Debug	(on|off) 'off'
			   ThreadSafe	(on|off) 'off'">
<!ENTITY % format.atts "Format		CDATA	#IMPLIED">
<!--=============== ELEMENT: Package =======================================-->
<!ELEMENT package (name, summary, maintainer, release, filelist)>
<!ATTLIST package
	%global.atts; 
	type (source | binary | empty) "empty"
>
<!--=============== ELEMENT: name ==========================================-->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	%global.atts; 
>
<!--=============== ELEMENT: summary =======================================-->
<!ELEMENT summary (#PCDATA)>
<!ATTLIST summary
	%global.atts; 
>
<!--=============== ELEMENT: maintainer ====================================-->
<!ELEMENT maintainer (initials, name, email)>
<!ATTLIST maintainer
	%global.atts; 
>
<!--=============== ELEMENT: initials ======================================-->
<!ELEMENT initials (#PCDATA)>
<!ATTLIST initials
	%global.atts; 
>
<!--=============== ELEMENT: email =========================================-->
<!ELEMENT email (#PCDATA)>
<!ATTLIST email
	%global.atts; 
>
<!--=============== ELEMENT: release =======================================-->
<!ELEMENT release (version, date, notes?)>
<!ATTLIST release
	%global.atts; 
>
<!--=============== ELEMENT: version =======================================-->
<!ELEMENT version (#PCDATA)>
<!ATTLIST version
	%global.atts; 
>
<!--=============== ELEMENT: date =========================================-->
<!ELEMENT date (#PCDATA)>
<!ATTLIST date
	%global.atts; 
>
<!--=============== ELEMENT: notes =========================================-->
<!ELEMENT notes (#PCDATA)>
<!ATTLIST notes
	%global.atts; 
>
<!--=============== ELEMENT: filelist ======================================-->
<!ELEMENT filelist (dir | file | libfile)*>
<!ATTLIST filelist
	%global.atts; 
>
<!--=============== ELEMENT: dir ===========================================-->
<!ELEMENT dir (#PCDATA)>
<!ATTLIST dir
        baseinstalldir CDATA #IMPLIED
	%global.atts; 
>
<!--=============== ELEMENT: file ==========================================-->
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	%global.atts; 
	%role.atts; 
	%extension.atts; 
	%format.atts; 
>
<!--=============== ELEMENT: libfile =======================================-->
<!ELEMENT libfile (libname,sources,includes?,libadd?)>
<!ATTLIST libfile
	%global.atts; 
	%role.atts; 
>
<!--=============== ELEMENT: libfile =======================================-->
<!ELEMENT libfile (libname,sources,includes?,libadd?)>
<!ATTLIST libfile
	%global.atts; 
	%role.atts; 
>
<!--=============== ELEMENT: libname =======================================-->
<!ELEMENT libname (#PCDATA)>
<!ATTLIST libname
	%global.atts; 
>
<!--=============== ELEMENT: sources =======================================-->
<!ELEMENT sources (#PCDATA)>
<!ATTLIST sources
	%global.atts; 
>
<!--=============== ELEMENT: libadd ========================================-->
<!ELEMENT libadd (#PCDATA)>
<!ATTLIST libadd
	%global.atts; 
>

=== php/php-src/ext/session/package.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE package SYSTEM "../pear/package.dtd">
<package>
 <name>session</name>
 <summary>Session handling functions</summary>
 <maintainers>
  <maintainer>
   <user>sascha</user>
   <name>Sascha Schumann</name>
   <email>sas@php.net</email>
   <role>lead</role>
  </maintainer>
  <maintainer>
   <user>andrei</user>
   <name>Andrei Zmievski</name>
   <email>andrei@php.net</email>
   <role>lead</role>
  </maintainer>
 </maintainers>
 <description>
Session support in PHP consists of a way to preserve certain data 
across subsequent accesses. This enables you to build more customized 
applications and increase the appeal of your web site.
 </description>
 <license>PHP</license>
 <release>
  <state>beta</state>
  <version>5.0.0rc1</version>
  <date>2004-03-19</date>
  <notes>
package.xml added to support installation using pear installer
  </notes>
  <filelist>
   <file role="doc" name="CREDITS"/>
   <file role="src" name="config.m4"/>
   <file role="src" name="config.w32"/>
   <file role="src" name="mod_files.c"/>
   <file role="src" name="mod_files.h"/>
   <file role="src" name="mod_files.sh"/>
   <file role="src" name="mod_mm.c"/>
   <file role="src" name="mod_mm.h"/>
   <file role="src" name="mod_user.c"/>
   <file role="src" name="mod_user.h"/>
   <file role="src" name="php_session.h"/>
   <file role="src" name="session.c"/>
   <file role="test" name="tests/001.phpt"/>
   <file role="test" name="tests/002.phpt"/>
   <file role="test" name="tests/bug25745.phpt"/>
   <file role="test" name="tests/001.phpt"/>
   <file role="test" name="tests/002.phpt"/>
   <file role="test" name="tests/003.phpt"/>
   <file role="test" name="tests/004.phpt"/>
   <file role="test" name="tests/005.phpt"/>
   <file role="test" name="tests/006.phpt"/>
   <file role="test" name="tests/007.phpt"/>
   <file role="test" name="tests/008-php4.2.3.phpt"/>
   <file role="test" name="tests/008.phpt"/>
   <file role="test" name="tests/009.phpt"/>
   <file role="test" name="tests/010.phpt"/>
   <file role="test" name="tests/011.phpt"/>
   <file role="test" name="tests/012.phpt"/>
   <file role="test" name="tests/013.phpt"/>
   <file role="test" name="tests/014.phpt"/>
   <file role="test" name="tests/015.phpt"/>
   <file role="test" name="tests/016.phpt"/>
   <file role="test" name="tests/017.phpt"/>
   <file role="test" name="tests/018.phpt"/>
   <file role="test" name="tests/019.phpt"/>
   <file role="test" name="tests/020.phpt"/>
   <file role="test" name="tests/021.phpt"/>
   <file role="test" name="tests/skipif.inc"/>
   <file role="test" name="tests/bug26862.phpt"/>
   <file role="test" name="tests/bug24592.phpt"/>
  </filelist>
  <deps>
   <dep type="php" rel="ge" version="5" />
  </deps>
 </release>
</package>
<!--
vim:et:ts=1:sw=1
-->

=== php/php-src/pear/package-db.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE package SYSTEM "package.dtd">
<package version="1.0">
  <name>DB</name>
  <summary>Database Abstraction Layer</summary>
  <description>
DB is a database abstraction layer providing:
 * an OO-style query API
 * a DSN (data source name) format for specifying database servers
 * prepare/execute (bind) emulation for databases that don't support
   it natively
 * a result object for each query response
 * portable error codes
 * sequence emulation
 * table information interface

DB layers itself on top of PHP's existing database extensions.  The
currently supported extensions are: dbase, fbsql, interbase, informix,
msql, mssql, mysql, oci8, odbc, pgsql and sybase.
</description>
  <license>PHP License</license>
  <maintainers>
    <maintainer>
      <user>ssb</user>
      <role>lead</role>
      <name>Stig Sæther Bakken</name>
      <email>stig@php.net</email>
    </maintainer>
    <maintainer>
      <user>cox</user>
      <role>developer</role>
      <name>Tomas V.V.Cox</name>
      <email>cox@idecnet.com</email>
    </maintainer>
  </maintainers>
  <release>
    <version>1.0</version>
    <state>stable</state>
    <date>2002-04-07</date>
    <notes>First packaged release.</notes>
    <filelist>
      <file role="php" baseinstalldir="/">DB.php</file>
      <dir name="DB">
	<file role="php">common.php</file>
	<file role="php">dbase.php</file>
	<file role="php">fbsql.php</file>
	<file role="php">ibase.php</file>
	<file role="php">ifx.php</file>
	<file role="php">msql.php</file>
	<file role="php">mssql.php</file>
	<file role="php">mysql.php</file>
	<file role="php">oci8.php</file>
	<file role="php">odbc.php</file>
	<file role="php">pgsql.php</file>
	<file role="php">sybase.php</file>
	<file role="php">storage.php</file>
	<file role="data">IDEAS</file>
	<file role="data">MAINTAINERS</file>
	<file role="data">STATUS</file>
	<file role="data">TESTERS</file>
	<dir name="tests">
	  <file role="test">db_error.phpt</file>
	  <file role="test">db_parsedsn.phpt</file>
	  <file role="test">db_factory.phpt</file>
	  <file role="test">db_ismanip.phpt</file>
	  <file role="test">db_error2.phpt</file>
	  <dir name="oci8">
	    <file role="test">06prepexec.phpt</file>
	    <file role="test">08affectedrows.phpt</file>
	    <file role="test">09numrows.phpt</file>
	    <file role="test">13limit.phpt</file>
	    <file role="test">05sequences.phpt</file>
	    <file role="test">07errornative.phpt</file>
	    <file role="test">01connect.phpt</file>
	    <file role="test">10errormap.phpt</file>
	    <file role="test">04numcols.phpt</file>
	    <file role="test">03simplequery.phpt</file>
	    <file role="test">02fetch.phpt</file>
	  </dir>
	  <dir name="odbc">
	    <file role="test">06prepexec.phpt</file>
	    <file role="test">09numrows.phpt</file>
	    <file role="test">07errornative.phpt</file>
	    <file role="test">01connect.phpt</file>
	    <file role="test">10errormap.phpt</file>
	    <file role="test">04numcols.phpt</file>
	    <file role="test">03simplequery.phpt</file>
	    <file role="test">02fetch.phpt</file>
	  </dir>
	  <dir name="ibase">
	    <file role="test">06prepexec.phpt</file>
	    <file role="test">05sequences.phpt</file>
	    <file role="test">01connect.phpt</file>
	    <file role="test">10errormap.phpt</file>
	    <file role="test">04numcols.phpt</file>
	    <file role="test">03simplequery.phpt</file>
	    <file role="test">02fetch.phpt</file>
	  </dir>
	  <dir name="mysql">
	    <file role="test">06prepexec.phpt</file>
	    <file role="test">08affectedrows.phpt</file>
	    <file role="test">09numrows.phpt</file>
	    <file role="test">13limit.phpt</file>
	    <file role="test">05sequences.phpt</file>
	    <file role="test">07errornative.phpt</file>
	    <file role="test">12tableinfo.phpt</file>
	    <file role="test">01connect.phpt</file>
	    <file role="test">10errormap.phpt</file>
	    <file role="test">04numcols.phpt</file>
	    <file role="test">03simplequery.phpt</file>
	    <file role="test">14fetchmode_object.phpt</file>
	    <file role="test">02fetch.phpt</file>
	  </dir>
	  <dir name="pgsql">
	    <file role="test">06prepexec.phpt</file>
	    <file role="test">11transact.phpt</file>
	    <file role="test">08affectedrows.phpt</file>
	    <file role="test">09numrows.phpt</file>
	    <file role="test">13limit.phpt</file>
	    <file role="test">05sequences.phpt</file>
	    <file role="test">07errornative.phpt</file>
	    <file role="test">01connect.phpt</file>
	    <file role="test">10errormap.phpt</file>
	    <file role="test">04numcols.phpt</file>
	    <file role="test">03simplequery.phpt</file>
	    <file role="test">14fetchmode_object.phpt</file>
	    <file role="test">02fetch.phpt</file>
	  </dir>
	  <dir name="driver">
	    <file role="test">06prepexec.phpt</file>
	    <file role="test">08affectedrows.phpt</file>
	    <file role="test">09numrows.phpt</file>
	    <file role="test">13limit.phpt</file>
	    <file role="test">05sequences.phpt</file>
	    <file role="test">15quote.phpt</file>
	    <file role="test">01connect.phpt</file>
	    <file role="test">10errormap.phpt</file>
	    <file role="test">04numcols.phpt</file>
	    <file role="test">03simplequery.phpt</file>
	    <file role="test">14fetchmode_object.phpt</file>
	    <file role="test">02fetch.phpt</file>
	  </dir>
	</dir>
      </dir>
    </filelist>
  </release>
</package>
